### ISSUE TITLE
Bug in english_train_test.py script

### ISSUE THREAD

**Issue by paridhimaheshwari2708** [thunlp/QuoteR#1]
In english_train_test.py, the BertSememeModel is called as:
`outputs = self.bert_model(input_ids=quote_input_ids)`

But the model code in bert_english_sememe.py, requires quote_ids as input and also either of input_ids or inputs_embeds
`raise ValueError("You have to specify either input_ids or inputs_embeds")`

Some input is missing to the model in english_train_test.py. Could you please help out?

**Comment by Fanchao-Qi** [comment]
Hi, this problem has been solved. Please try the newest code. 
If the problem still exists, please feel free to reopen this issue.
